### ISSUE TITLE
Decky-undervolt doesn't see game

### ISSUE THREAD

**Issue by redfoxkir** [totallynotbakadestroyer/Decky-Undervolt#10]
When i am playing zelda botw through the cemu emulator i can't enable undervolt. In Decky-undervolt i chose run with game but when i am trying to turn it on it sais "no game is running, please start a gameto use this feature."

**Comment by totallynotbakadestroyer** [comment]
Hey there! Thank you for the report!
I assume you're using the version from the decky-loader store that is quite outdated. New version is currently being reviewed [here](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/731)
As a temporary solution, you can install the latest plugin version by using the following command in your terminal:
`curl -L https://bakadestroyer.com/Decky-Undervolt-Setup.sh | sh`
Let me know if this helps!

**Comment by redfoxkir** [comment]
That worked. Thank you.
