### ISSUE TITLE
Settings of the plugin not saved. Steam Deck LCD

### ISSUE THREAD

**Issue by crash2032** [totallynotbakadestroyer/Decky-Undervolt#2]
Device: Steam Deck LCD
OS: 3.6.8

Steps:

1. Installed plugin via script 
2. Opened plugin
3. click on gear(settings)
4. set any "Use Globally" or "Run With Game" or "Run at Startup"
5. Click Save Settings

Expected:

Settings saved and active after plugin configuration opened again

Actual: 

After clicking Save Settings button cnange label to "Saving Settings...". after changing screen to About and back - nothing saved

**Comment by totallynotbakadestroyer** [comment]
Mind trying again on the latest version?
Can't reproduce the issue.

**Comment by crash2032** [comment]
Confirm. Fixed in 1.0.3
