### ISSUE TITLE
Not working on Bazzite (Steam Deck LCD)

### ISSUE THREAD

**Issue by Tobe95** [totallynotbakadestroyer/Decky-Undervolt#4]
On Bazzite, setting and applying any undervolt amount has no effect. Even though the log reads "Undervolt applied" at some point, there appears to be an issue with OpenSSL, specifically libldap.so.2:

```
[ERROR]: RYZENADJ: sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/libexec/sudo/sudoers.so: /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0
sudo: fatal error, unable to load plugins
```
From what I could gather, this is due to a difference with OpenSSL being compiled with the `enable-md2` option on Bazzite, but not on SteamOS. 

Is there any chance to get this working?

Device: Steam Deck LCD
OS: Bazzite 3.6.0 (Fedora 40)
Decky-Undervolt v1.0.5

[2024-08-08 19.11.48.log](https://github.com/user-attachments/files/16552400/2024-08-08.19.11.48.log)

**Comment by totallynotbakadestroyer** [comment]
Bazzite and other OS are currently unsupported. Consider switching back to Steam OS.
However will try to resolve it. Thank you for the report!
